### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aykevl** [privacybydesign/irma_idin_issuer#1]
- [ ] investigate 400 error
 - [ ] fix transactions without end status
 - [ ] remove dead code and unused options in JSON files
 - [ ] improve skip button in step 1 (form validation, bank selection, etc.)
 - [ ] document configuration files, add config files to .gitignore
 - [ ] walk through UI, avoid all inconsistencies and error messages

@sietseringers anything missing?

**Comment by sietseringers** [comment]
One thing:
  * [ ]  Translate all messages and ensure that `messages.nl.js` is loaded
